version: '3.8'

services:
  app:
    build:
      context: '.'
      dockerfile: './docker/Dockerfile'
    volumes:
      - '.:/app'
    ports:
      - '3333:3333'
  db:
    image: mariadb:10.3.37
    volumes:
      - './docker/database:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app
